import '@/../public/css/animate.css'
import '@/../public/css/bootstrap.min.css'
import '@/../public/css/fonts.css'
import '@/../public/css/flaticon.css'
import '@/../public/css/font-awesome.css'
import '@/../public/css/owl.carousel.css'
import '@/../public/css/owl.theme.default.css'
import '@/../public/css/nice-select.css'
import '@/../public/css/swiper.css'
import '@/../public/css/magnific-popup.css'
import '@/../public/css/style.css'
import '@/../public/css/responsive.css'

import { Inter } from 'next/font/google'
import './globals.css'
import Script from 'next/script'
import SupabaseProvider from '@/providers/SupabaseProvider'
import Player from '@/components/new/player/Player'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Script src="http://localhost:3000/js/jquery-3.3.1.min.js" />
        <Script src="http://localhost:3000/js/bootstrap.min.js" />
        <Script src="http://localhost:3000/js/modernizr.js" />
        <Script src="http://localhost:3000/js/plugin.js" />
        <Script src="http://localhost:3000/js/jquery.nice-select.min.js" />
        <Script src="http://localhost:3000/js/jquery.inview.min.js" />
        <Script src="http://localhost:3000/js/jquery.magnific-popup.js" />
        <Script src="http://localhost:3000/js/swiper.min.js" />
        <Script src="http://localhost:3000/js/comboTreePlugin.js" />
        <Script src="http://localhost:3000/js/mp3/jquery.jplayer.min.js" />
        <Script src="http://localhost:3000/js/mp3/jplayer.playlist.js" />
        <Script src="http://localhost:3000/js/owl.carousel.js" />
        <Script src="http://localhost:3000/js/mp3/player.js" />
        <Script src="http://localhost:3000/js/custom.js" />

        <SupabaseProvider>
          <div class="cursor" />

          <div id="sidebar" className="bounce-to-right index3_sidebar">
            <div id="toggle_close">×</div>
            <div id="cssmenu">
              <a href="index.html">
                <img src="images/logo3.png" alt="logo" />
              </a>
              <ul className="sidebb">
                <li className="has-sub">
                  <a href="#">
                    <i className="flaticon-home" />
                    index
                  </a>
                  <ul>
                    <li>
                      <a href="index.html">
                        {" "}
                        <i className="flaticon-home" />
                        index I
                      </a>
                    </li>
                    <li>
                      <a href="index2.html">
                        <i className="flaticon-home" />
                        index II
                      </a>
                    </li>
                    <li>
                      <a href="index3.html">
                        <i className="flaticon-home" />
                        index III
                      </a>
                    </li>
                    <li>
                      <a href="index4.html">
                        <i className="flaticon-home" />
                        index IV
                      </a>
                    </li>
                  </ul>
                </li>
                <li className="has-sub">
                  <a href="#">
                    <i className="flaticon-album" />
                    albums
                  </a>
                  <ul>
                    <li>
                      <a href="album.html">
                        {" "}
                        <i className="flaticon-vinyl" />
                        album
                      </a>
                    </li>
                    <li>
                      <a href="album_list.html">
                        <i className="flaticon-playlist-1" />
                        album list
                      </a>
                    </li>
                    <li>
                      <a href="artist.html">
                        <i className="flaticon-headphones" />
                        artist
                      </a>
                    </li>
                    <li>
                      <a href="artist_single.html">
                        <i className="flaticon-speaker" />
                        artist single
                      </a>
                    </li>
                  </ul>
                </li>
                <li className="has-sub">
                  <a href="#">
                    <i className="flaticon-playlist-3" />
                    browse music
                  </a>
                  <ul>
                    <li>
                      <a href="add_playlist.html">
                        <i className="flaticon-music" />
                        add playlist
                      </a>
                    </li>
                    <li>
                      <a href="free_music.html">
                        <i className="flaticon-music-1" />
                        free music
                      </a>
                    </li>
                    <li>
                      <a href="genres.html">
                        <i className="flaticon-files-and-folders" />
                        genres
                      </a>
                    </li>
                    <li>
                      <a href="genres_single.html">
                        <i className="flaticon-smartphone" />
                        genres single
                      </a>
                    </li>
                    <li>
                      <a href="stations.html">
                        <i className="flaticon-radio" />
                        stations
                      </a>
                    </li>
                  </ul>
                </li>
                <li className="has-sub">
                  <a href="#">
                    <i className="flaticon-clock" />
                    music events
                  </a>
                  <ul>
                    <li>
                      <a href="events.html">
                        <i className="flaticon-calendar" />
                        events
                      </a>
                    </li>
                    <li>
                      <a href="event_single.html">
                        <i className="flaticon-files-and-folders" />
                        event single
                      </a>
                    </li>
                  </ul>
                </li>
                <li className="has-sub">
                  <a href="#">
                    <i className="flaticon-playlist-1" />
                    your music
                  </a>
                  <ul>
                    <li>
                      <a href="download.html">
                        <i className="flaticon-download" />
                        download
                      </a>
                    </li>
                    <li>
                      <a href="favourite.html">
                        <i className="flaticon-heart" />
                        favourite
                      </a>
                    </li>
                    <li>
                      <a href="history.html">
                        <i className="flaticon-clock" />
                        history
                      </a>
                    </li>
                    <li>
                      <a href="free_music.html">
                        <i className="flaticon-music-1" />
                        free_music
                      </a>
                    </li>
                  </ul>
                </li>
                <li className="has-sub">
                  <a href="#">
                    <i className="flaticon-shopping-bag" /> shop
                  </a>
                  <ul>
                    <li>
                      <a href="shop_sidebar.html">
                        <i className="flaticon-smartphone" />
                        shop sidebar
                      </a>
                    </li>
                    <li>
                      <a href="shop_single.html">
                        {" "}
                        <i className="flaticon-info" />
                        shop single
                      </a>
                    </li>
                  </ul>
                </li>
                <li className="has-sub">
                  <a href="#">
                    <i className="flaticon-playlist" /> music blog
                  </a>
                  <ul>
                    <li>
                      <a href="blog_categories.html">
                        <i className="flaticon-vinyl" />
                        blog category I
                      </a>
                    </li>
                    <li>
                      <a href="blog_category2.html">
                        {" "}
                        <i className="flaticon-album" />
                        blog category II
                      </a>
                    </li>
                    <li>
                      <a href="blog_single.html">
                        {" "}
                        <i className="flaticon-globe" />
                        blog single
                      </a>
                    </li>
                  </ul>
                </li>
                <li>
                  <a href="contact_us.html">
                    <i className="flaticon-internet" />
                    contact us
                  </a>
                </li>
                <li>
                  <a href="pricing_plan.html">
                    <i className="flaticon-bell" />
                    pricing plan
                  </a>
                </li>
                <li>
                  <a href="error_page.html">
                    <i className="flaticon-trash" />
                    error 404
                  </a>
                </li>
              </ul>
              <div className="lang_apply_btn">
                <ul>
                  <li>
                    <a href="#">
                      {" "}
                      <i className="flaticon-play-button" />
                      create
                    </a>
                  </li>
                </ul>
              </div>
            </div>
          </div>

          <div className="m24_navi_main_wrapper index2_main_header index3_main_header m24_cover">
            <div className="container-fluid">
              <div className="m24_logo_wrapper">
                <div className="m24_logo_div">
                  <a href="index.html">
                    <img src="images/logo3.png" alt="logo" />
                  </a>
                </div>
                <div id="toggle">
                  <a href="#">
                    <i className="flaticon-menu-1" />
                  </a>
                </div>
              </div>
              <div className="m24_header_right_Wrapper d-none d-sm-none d-md-none d-lg-none d-xl-block">
                <div className="m24_signin_wrapper">
                  <a href="#" data-toggle="modal" data-target="#login_modal">
                    <img src="images/pf.png" alt="img" />
                    <div className="login_top_wrapper">
                      <p>login/register</p>
                    </div>
                  </a>
                </div>
                <div className="crm_message_dropbox_wrapper">
                  <div className="nice-select budge_noti_wrapper" tabIndex={0}>
                    {" "}
                    <span className="current budge_noti">
                      <i className="flaticon-bell" />
                    </span>
                    <ul className="list pullDown">
                      <li>
                        <a href="#">3 New notifications</a>
                      </li>
                      <li>
                        <div className="crm_mess_main_box_wrapper">
                          <div className="crm_mess_img_wrapper">
                            <img src="images/nt1.jpg" alt="img" />
                          </div>
                          <div className="crm_mess_img_cont_wrapper">
                            <h4>
                              Walking Promises <span>01:30PM</span>
                            </h4>
                            <p>Ava Cornish</p>
                          </div>
                        </div>
                      </li>
                      <li>
                        <div className="crm_mess_main_box_wrapper">
                          <div className="crm_mess_img_wrapper">
                            <img src="images/nt2.jpg" alt="img" />
                          </div>
                          <div className="crm_mess_img_cont_wrapper">
                            <h4>
                              Until I Met You <span>01:30PM</span>
                            </h4>
                            <p>diu pokal</p>
                          </div>
                        </div>
                      </li>
                      <li>
                        <div className="crm_mess_main_box_wrapper">
                          <div className="crm_mess_img_wrapper">
                            <img src="images/nt3.jpg" alt="img" />
                          </div>
                          <div className="crm_mess_img_cont_wrapper">
                            <h4>
                              merry with you<span>01:30PM</span>
                            </h4>
                            <p>love song</p>
                          </div>
                        </div>
                      </li>
                      <li>
                        <div className="crm_mess_all_main_box_wrapper">
                          <p>
                            <a href="#">See All</a>
                          </p>
                        </div>
                      </li>
                    </ul>
                  </div>
                </div>
              </div>
              <div className="m24_navigation_wrapper">
                <div className="mainmenu d-xl-block d-lg-block d-md-none d-sm-none d-none">
                  <ul className="main_nav_ul">
                    <li className="has-mega gc_main_navigation">
                      <a href="#" className="gc_main_navigation">
                        browse <i className="flaticon-down-arrow" />
                      </a>
                      <ul className="navi_2_dropdown">
                        <li className="parent">
                          <a href="add_playlist.html">
                            <i className="fas fa-caret-right" />
                            featured playlist
                          </a>
                        </li>
                        <li className="parent">
                          <a href="artist.html">
                            <i className="fas fa-caret-right" />
                            top artists
                          </a>
                        </li>
                        <li className="parent">
                          <a href="genres.html">
                            <i className="fas fa-caret-right" />
                            new genres
                          </a>
                        </li>
                        <li className="parent">
                          <a href="album.html">
                            <i className="fas fa-caret-right" />
                            all albums
                          </a>
                        </li>
                        <li className="parent">
                          <a href="album_list.html">
                            <i className="fas fa-caret-right" />
                            weekly tops
                          </a>
                        </li>
                      </ul>
                    </li>
                    <li>
                      <a href="stations.html" className="gc_main_navigation">
                        radio
                      </a>
                    </li>
                    <li className="has-mega gc_main_navigation">
                      <a href="#" className="gc_main_navigation">
                        more <i className="flaticon-down-arrow" />
                      </a>
                      <ul className="navi_2_dropdown">
                        <li className="parent">
                          <a href="contact_us.html">
                            <i className="fas fa-caret-right" />
                            contact
                          </a>
                        </li>
                        <li className="parent">
                          <a href="pricing_plan.html">
                            <i className="fas fa-caret-right" /> pricing plan{" "}
                          </a>
                        </li>
                        <li className="parent">
                          <a href="error_page.html">
                            <i className="fas fa-caret-right" /> error page{" "}
                          </a>
                        </li>
                        <li className="parent">
                          <a href="favourite.html">
                            <i className="fas fa-caret-right" /> favourite song{" "}
                          </a>
                        </li>
                      </ul>
                    </li>
                  </ul>
                </div>
                {/* mainmenu end */}
                <div className="navi_searchbar_wrapper">
                  <i className="flaticon-magnifying-glass" />
                  <input
                    type="text"
                    id="justAnotherInputBox"
                    placeholder="Search for Songs, Artists, Playlists and More.."
                  />
                </div>
                <div className="d-block d-sm-block d-md-block d-lg-block d-xl-none">
                  <div className="search_bar index3_search_bar">
                    <div className="res_search_bar" id="search_button">
                      {" "}
                      <i className="fa fa-ellipsis-v" />
                    </div>
                    <div id="search_open" className="res_search_box">
                      <div className="lang_list_wrapper responsive_search_toggle">
                        <a href="#" data-toggle="modal" data-target="#myModal">
                          languages <i className="fas fa-language" />
                        </a>
                      </div>
                      <div className="m24_signin_wrapper responsive_search_toggle">
                        <a href="#" data-toggle="modal" data-target="#login_modal">
                          <img src="images/pf.png" alt="img" />
                          <div className="login_top_wrapper">
                            <p>login/register</p>
                          </div>
                        </a>
                      </div>
                      <div className="crm_message_dropbox_wrapper responsive_search_toggle">
                        <div className="nice-select budge_noti_wrapper" tabIndex={0}>
                          {" "}
                          <span className="current budge_noti">
                            <i className="flaticon-bell" />
                          </span>
                          <p className="notify_para">notifications</p>
                          <ul className="list">
                            <li>
                              <a href="#">3 New notifications </a>
                            </li>
                            <li>
                              <div className="crm_mess_main_box_wrapper">
                                <div className="crm_mess_img_wrapper">
                                  <img src="images/nt1.jpg" alt="img" />
                                </div>
                                <div className="crm_mess_img_cont_wrapper">
                                  <h4>
                                    Walking Promises <span>01:30PM</span>
                                  </h4>
                                  <p>Ava Cornish</p>
                                </div>
                              </div>
                            </li>
                            <li>
                              <div className="crm_mess_main_box_wrapper">
                                <div className="crm_mess_img_wrapper">
                                  <img src="images/nt2.jpg" alt="img" />
                                </div>
                                <div className="crm_mess_img_cont_wrapper">
                                  <h4>
                                    Until I Met You <span>01:30PM</span>
                                  </h4>
                                  <p>diu pokal</p>
                                </div>
                              </div>
                            </li>
                            <li>
                              <div className="crm_mess_main_box_wrapper">
                                <div className="crm_mess_img_wrapper">
                                  <img src="images/nt3.jpg" alt="img" />
                                </div>
                                <div className="crm_mess_img_cont_wrapper">
                                  <h4>
                                    merry with you<span>01:30PM</span>
                                  </h4>
                                  <p>love song</p>
                                </div>
                              </div>
                            </li>
                            <li>
                              <div className="crm_mess_all_main_box_wrapper">
                                <p>
                                  <a href="#">See All</a>
                                </p>
                              </div>
                            </li>
                          </ul>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div className="m24_navi_langauage_box d-none d-sm-none d-md-none d-lg-none d-xl-block">
                  <div className="lang_list_wrapper">
                    <a href="#" data-toggle="modal" data-target="#myModal">
                      languages <i className="fas fa-language" />
                    </a>
                  </div>
                  <div className="theme-switch-wrapper d-none d-sm-none d-md-none d-lg-none d-xl-none">
                    <label className="theme-switch" htmlFor="checkbox">
                      <input type="checkbox" id="checkbox" />
                      <span className="slider round" />
                    </label>
                  </div>
                </div>
              </div>
            </div>
          </div>

          {children}
          
          {/* Add player here */}
          <Player/>
        </SupabaseProvider>
      </body>
    </html>
  )
}
